#!/bin/bash
export token=$TOKEN
export CI_CHANNEL_ID=-1001721818658
git clone --depth=1 https://github.com/Brew-Tea/TLinux-Kernel -b blazing && cd TLinux-Kernel
wget https://github.com/Brew-Tea/scripts-build/raw/master/x86/build.sh
chmod +x build.sh
./build.sh --debian
